# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options.ui'
#
# Created: Tue Feb 21 17:22:34 2017
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(469, 433)
        Dialog.setMinimumSize(QtCore.QSize(424, 430))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 390, 441, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 441, 371))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 120, 411, 91))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cb_ncf = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_ncf.setObjectName(_fromUtf8("cb_ncf"))
        self.gridLayout_2.addWidget(self.cb_ncf, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 2)
        self.cb_ncl = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_ncl.setObjectName(_fromUtf8("cb_ncl"))
        self.gridLayout_2.addWidget(self.cb_ncl, 2, 0, 1, 1)
        self.cb_incr = QtGui.QCheckBox(self.gridLayoutWidget)
        self.cb_incr.setObjectName(_fromUtf8("cb_incr"))
        self.gridLayout_2.addWidget(self.cb_incr, 1, 1, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 411, 91))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.sb_before = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.sb_before.setObjectName(_fromUtf8("sb_before"))
        self.gridLayout_3.addWidget(self.sb_before, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 2)
        self.sp_after = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.sp_after.setObjectName(_fromUtf8("sp_after"))
        self.gridLayout_3.addWidget(self.sp_after, 2, 2, 1, 1)
        self.sp_cloze = QtGui.QSpinBox(self.gridLayoutWidget_2)
        self.sp_cloze.setObjectName(_fromUtf8("sp_cloze"))
        self.gridLayout_3.addWidget(self.sp_cloze, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayoutWidget = QtGui.QWidget(self.tab_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 421, 306))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.le_og = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_og.setObjectName(_fromUtf8("le_og"))
        self.gridLayout.addWidget(self.le_og, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.le_fl = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_fl.setObjectName(_fromUtf8("le_fl"))
        self.gridLayout.addWidget(self.le_fl, 8, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 2)
        self.le_sc = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_sc.setObjectName(_fromUtf8("le_sc"))
        self.gridLayout.addWidget(self.le_sc, 5, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 6, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.le_tx = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_tx.setObjectName(_fromUtf8("le_tx"))
        self.gridLayout.addWidget(self.le_tx, 7, 2, 1, 1)
        self.le_tt = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_tt.setObjectName(_fromUtf8("le_tt"))
        self.gridLayout.addWidget(self.le_tt, 3, 2, 1, 1)
        self.le_st = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_st.setObjectName(_fromUtf8("le_st"))
        self.gridLayout.addWidget(self.le_st, 6, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 7, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 8, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 9, 1, 1, 2)
        self.le_rk = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_rk.setObjectName(_fromUtf8("le_rk"))
        self.gridLayout.addWidget(self.le_rk, 4, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 10, 1, 1, 1)
        self.le_model = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_model.setObjectName(_fromUtf8("le_model"))
        self.gridLayout.addWidget(self.le_model, 10, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Cloze Generator Options", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_ncf.setToolTip(QtGui.QApplication.translate("Dialog", "Don\'t provide any context cues for first cloze item", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_ncf.setText(QtGui.QApplication.translate("Dialog", "No Context for First Item", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "<b>Handling of First and Last Items</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_ncl.setToolTip(QtGui.QApplication.translate("Dialog", "Don\'t provide any context cues for last cloze item", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_ncl.setText(QtGui.QApplication.translate("Dialog", "No Context for Last Item", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_incr.setToolTip(QtGui.QApplication.translate("Dialog", "For notes that have multiple clozes revealed per card,<br>gradually build up to full reveal count at the start,<br>and vice-versa in the end", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_incr.setText(QtGui.QApplication.translate("Dialog", "Incremental Ends", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_before.setToolTip(QtGui.QApplication.translate("Dialog", "Number of context cues before the prompt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "<b>Default Cloze Settings</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.sp_after.setToolTip(QtGui.QApplication.translate("Dialog", "Number of context cues after the prompt", None, QtGui.QApplication.UnicodeUTF8))
        self.sp_cloze.setToolTip(QtGui.QApplication.translate("Dialog", "Number of items to prompt for per card", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Context Before", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Cloze Length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Context After", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Remarks", None, QtGui.QApplication.UnicodeUTF8))
        self.le_og.setToolTip(QtGui.QApplication.translate("Dialog", "Define a custom name for the field in question", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.le_fl.setToolTip(QtGui.QApplication.translate("Dialog", "Define a custom name for the field in question", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "<b>Field Names</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.le_sc.setToolTip(QtGui.QApplication.translate("Dialog", "Define a custom name for the field in question", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Original", None, QtGui.QApplication.UnicodeUTF8))
        self.le_tx.setToolTip(QtGui.QApplication.translate("Dialog", "Define a custom name for the field in question", None, QtGui.QApplication.UnicodeUTF8))
        self.le_tt.setToolTip(QtGui.QApplication.translate("Dialog", "Define a custom name for the field in question", None, QtGui.QApplication.UnicodeUTF8))
        self.le_st.setToolTip(QtGui.QApplication.translate("Dialog", "Define a custom name for the field in question", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Full", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "<b>Custom Note Type</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.le_rk.setToolTip(QtGui.QApplication.translate("Dialog", "Define a custom name for the field in question", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.le_model.setToolTip(QtGui.QApplication.translate("Dialog", "Name of custom note type to use instead of the default one", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Advanced", None, QtGui.QApplication.UnicodeUTF8))

