#!/bin/bash
#
# generate python files based on the designer ui files. pyuic4 and pyrcc4
# should be on the path.
#
# based on build_ui.sh by Damien Elmes

if [ ! -d "designer" ]
then
    echo "Please run this from the project root"
    exit
fi

form_dir4="cloze_overlapper/forms4"
form_dir5="cloze_overlapper/forms5"
init4="$form_dir4/__init__.py"
init5="$form_dir5/__init__.py"

mkdir -p "$form_dir4"
mkdir -p "$form_dir5"
echo "Writing init files..."
echo "# This file was auto-generated by build_ui.sh. Don't edit." > "$init4"
echo "# This file was auto-generated by build_ui.sh. Don't edit." > "$init5"

echo "Generating forms..."
for i in designer/*.ui; do
    name="${i##*/}"
    base="${name%.*}"
    echo "Generating $base"
    out4="$form_dir4/${base}.py"
    out5="$form_dir5/${base}.py"
    pyuic4 "$i" -o "$out4"
    pyuic5 "$i" -o "$out5"
done

echo "Done."