#!/bin/bash
#
# generate python files based on the designer ui files. pyuic4 and pyrcc4
# should be on the path.
#
# based on build_ui.sh by Damien Elmes

if [ ! -d "designer" ]
then
    echo "Please run this from the project root"
    exit
fi

form_dir="cloze_overlapper/forms"
init="$form_dir/__init__.py"

mkdir -p "$form_dir"
echo "Writing init file..."
echo "# This file was auto-generated by build_ui.sh. Don't edit." > "$init"

echo "Generating forms..."
for i in designer/*.ui; do
    name="${i##*/}"
    base="${name%.*}"
    echo "Generating $base"
    out="$form_dir/${base}.py"
    pyuic4 "$i" -o "$out"
done

echo "Done."